title: [Khalid's Portfolio of Cybersecurity Projects]
description: This portfolio presents Khalid’s journey in cybersecurity, with projects ranging from penetration testing and vulnerability analysis to capture-the-flag (CTF) challenges. Each project reflects problem-solving skills, technical knowledge, and a strong commitment to building secure digital environments.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
